Update gce-cloud-delete

diff --git a/cloud-init/gce-cloud-delete b/cloud-init/gce-cloud-delete
--- a/cloud-init/gce-cloud-delete
+++ b/cloud-init/gce-cloud-delete
@@ -137,24 +137,24 @@ fi
 
 #----------------------------------------------------------------
 # Check 2: Check if cloud provider
-digikubeCloudProvider=$(getConfigValue "cloud.provider")
-if [[ -z ${digikubeCloudProvider} ]]; then
-	echo "ERROR: Cloud provider not specified in config.  Exiting..."
-	exit 1
-else
-	# TO DO: This has to be restructured for each of the cloud provider.
-	if [[ "${digikubeCloudProvider}" != "gce" ]] && [[ "${digikubeCloudProvider}" != "aws" ]] && [[ "${digikubeCloudProvider}" != "azure" ]]; then
-		echo "ERROR: Invalid cloud provider (${digikubeCloudProvider}) specified in config.  Exiting..."
-		exit 1
-	fi
-fi
-currentCloudProvider="gce"			#TO DO: Auto detect current cloud provider
-if [[ "${currentCloudProvider}" == "${digikubeCloudProvider}" ]]; then
-	echo "INFO: Using ${digikubeCloudProvider} as the cloud provider for Digikube."
-else
-	echo "ERROR: Current cloud provider (${currentCloudProvider}) is not same as the name set in config (${digikubeCloudProvider}).  Exiting..."
-	exit 1
-fi
+#digikubeCloudProvider=$(getConfigValue "cloud.provider")
+#if [[ -z ${digikubeCloudProvider} ]]; then
+#	echo "ERROR: Cloud provider not specified in config.  Exiting..."
+#	exit 1
+#else
+#	# TO DO: This has to be restructured for each of the cloud provider.
+#	if [[ "${digikubeCloudProvider}" != "gce" ]] && [[ "${digikubeCloudProvider}" != "aws" ]] && [[ "${digikubeCloudProvider}" != "azure" ]]; then
+#		echo "ERROR: Invalid cloud provider (${digikubeCloudProvider}) specified in config.  Exiting..."
+#		exit 1
+#	fi
+#fi
+#currentCloudProvider="gce"			#TO DO: Auto detect current cloud provider
+#if [[ "${currentCloudProvider}" == "${digikubeCloudProvider}" ]]; then
+#	echo "INFO: Using ${digikubeCloudProvider} as the cloud provider for Digikube."
+#else
+#	echo "ERROR: Current cloud provider (${currentCloudProvider}) is not same as the name set in config (${digikubeCloudProvider}).  Exiting..."
+#	exit 1
+#fi
 
 #----------------------------------------------------------------
 # Check 2: Verify the mandatory config values
@@ -170,7 +170,7 @@ if [[ -z ${digikubeCloudAdminUser} ]]; then
 else
 	currentCloudAdminUser=$(whoami)
 	if [[ "${currentCloudAdminUser}" == "${digikubeCloudAdminUser}" ]]; then
-		echo "INFO: Using ${digikubeCloudAdminUser} identity for installing Digikube."
+		echo "INFO: Using ${digikubeCloudAdminUser} identity for deleting Digikube."
 	else
 		echo "ERROR: Current user (${currentCloudAdminUser}) is not same as the name set in config (${digikubeCloudAdminUser}).  Exiting..."
 		exit 1
@@ -199,14 +199,14 @@ fi
 
 #----------------------------------------------------------------
 # Check 5: Check if the cloud project region specified
-digikubeCloudProjectRegion=$(getConfigValue "cloud.project.region")
-if [[ -z ${digikubeCloudProjectRegion} ]]; then
-	echo "ERROR: Cloud project region not specified in config.  Exiting..."
-	exit 1
-else
-	# TO DO: Validate if the cloud region is valid for the cloud provider selected.
-	echo "INFO: Using ${digikubeCloudProjectRegion} as the default region for Digikube."
-fi
+#digikubeCloudProjectRegion=$(getConfigValue "cloud.project.region")
+#if [[ -z ${digikubeCloudProjectRegion} ]]; then
+#	echo "ERROR: Cloud project region not specified in config.  Exiting..."
+#	exit 1
+#else
+#	# TO DO: Validate if the cloud region is valid for the cloud provider selected.
+#	echo "INFO: Using ${digikubeCloudProjectRegion} as the default region for Digikube."
+#fi
 
 #----------------------------------------------------------------
 # Check 6: Check if the cloud project zone specified
@@ -243,20 +243,21 @@ if [[ "${confirmation}" == "y" ]]; then
 	echo "INFO: Attempting to delete the Digikube environment for cluster ${digikubeClusterFullName}"
 else
 	echo "INFO: Aborting the Digikube environment deletion"
+	exit 0
 fi
 
 #----------------------------------------------------------------
 # Check 7: Check bucket config
-digikubeCloudBucketClass=$(getConfigValue "cloud.bucket.class")
-if [[ -z ${digikubeCloudBucketClass} ]]; then
-	echo "ERROR: Cloud bucket class not specified in config.  Exiting..."
-	exit 1
-else
-	if [[ "${digikubeCloudBucketClass}" != "STANDARD" ]] && [[ "${digikubeCloudBucketClass}" != "PREMIUM" ]]; then
-		echo "ERROR: Invalid cloud bucket class (${digikubeCloudBucketClass}) specified in config.  Exiting..."
-		exit 1
-	fi
-fi
+#digikubeCloudBucketClass=$(getConfigValue "cloud.bucket.class")
+#if [[ -z ${digikubeCloudBucketClass} ]]; then
+#	echo "ERROR: Cloud bucket class not specified in config.  Exiting..."
+#	exit 1
+#else
+#	if [[ "${digikubeCloudBucketClass}" != "STANDARD" ]] && [[ "${digikubeCloudBucketClass}" != "PREMIUM" ]]; then
+#		echo "ERROR: Invalid cloud bucket class (${digikubeCloudBucketClass}) specified in config.  Exiting..."
+#		exit 1
+#	fi
+#fi
 
 #----------------------------------------------------------------
 # Check 8: Check bastion host config
@@ -267,26 +268,26 @@ if [[ -z ${digikubeBastionHostName} ]]; then
 	exit 1
 else
 	# TO DO: Verify the correctness of the following config values for bastion host.
-	digikubeBastionHostMachineType=$(getConfigValue "cloud.bastionHost.machineType")
-	echo "INFO: Bastion host machine type is ${digikubeBastionHostMachineType}"
-	digikubeBastionHostNetworkTier=$(getConfigValue "cloud.bastionHost.networkTier")
-	echo "INFO: Bastion host network tier is ${digikubeBastionHostNetworkTier}"
-	digikubeBastionHostPreemptible=$(getConfigValue "cloud.bastionHost.preemptible")
-	echo "INFO: Bastion host preemptibility is ${digikubeBastionHostPreemptible}"
-	digikubeBastionHostTagIdentifier=$(getConfigValue "cloud.bastionHost.tagIdentifier")
-	echo "INFO: Bastion host tag identifier is ${digikubeBastionHostTagIdentifier}"
-	digikubeBastionHostTags="${digikubeBastionHostTagIdentifier},http-server,https-server"
-	echo "INFO: Bastion host tags are ${digikubeBastionHostTags}"
-	digikubeBastionHostImage=$(getConfigValue "cloud.bastionHost.image")
-	echo "INFO: Bastion host image is ${digikubeBastionHostImage}"
-	digikubeBastionHostImageProject=$(getConfigValue "cloud.bastionHost.imageProject")
-	echo "INFO: Bastion host image project is ${digikubeBastionHostImageProject}"
-	digikubeBastionHostBootDiskSize=$(getConfigValue "cloud.bastionHost.bootDiskSize")
-	echo "INFO: Bastion host boot disk size is ${digikubeBastionHostBootDiskSize}"
-	digikubeBastionHostBootDiskType=$(getConfigValue "cloud.bastionHost.bootDiskType")
-	echo "INFO: Bastion host boot disk type is ${digikubeBastionHostBootDiskType}"
-	digikubeBastionHostLabels="type=${digikubeBastionHostTagIdentifier},creator=digikube"
-	echo "INFO: Bastion host labels are ${digikubeBastionHostLabels}"
+	#digikubeBastionHostMachineType=$(getConfigValue "cloud.bastionHost.machineType")
+	#echo "INFO: Bastion host machine type is ${digikubeBastionHostMachineType}"
+	#digikubeBastionHostNetworkTier=$(getConfigValue "cloud.bastionHost.networkTier")
+	#echo "INFO: Bastion host network tier is ${digikubeBastionHostNetworkTier}"
+	#digikubeBastionHostPreemptible=$(getConfigValue "cloud.bastionHost.preemptible")
+	#echo "INFO: Bastion host preemptibility is ${digikubeBastionHostPreemptible}"
+	#digikubeBastionHostTagIdentifier=$(getConfigValue "cloud.bastionHost.tagIdentifier")
+	#echo "INFO: Bastion host tag identifier is ${digikubeBastionHostTagIdentifier}"
+	#digikubeBastionHostTags="${digikubeBastionHostTagIdentifier},http-server,https-server"
+	#echo "INFO: Bastion host tags are ${digikubeBastionHostTags}"
+	#digikubeBastionHostImage=$(getConfigValue "cloud.bastionHost.image")
+	#echo "INFO: Bastion host image is ${digikubeBastionHostImage}"
+	#digikubeBastionHostImageProject=$(getConfigValue "cloud.bastionHost.imageProject")
+	#echo "INFO: Bastion host image project is ${digikubeBastionHostImageProject}"
+	#digikubeBastionHostBootDiskSize=$(getConfigValue "cloud.bastionHost.bootDiskSize")
+	#echo "INFO: Bastion host boot disk size is ${digikubeBastionHostBootDiskSize}"
+	#digikubeBastionHostBootDiskType=$(getConfigValue "cloud.bastionHost.bootDiskType")
+	#echo "INFO: Bastion host boot disk type is ${digikubeBastionHostBootDiskType}"
+	#digikubeBastionHostLabels="type=${digikubeBastionHostTagIdentifier},creator=digikube"
+	#echo "INFO: Bastion host labels are ${digikubeBastionHostLabels}"
 fi
 
 #################################################################
