Update gce-cloud-delete

diff --git a/cloud-init/gce-cloud-delete b/cloud-init/gce-cloud-delete
--- a/cloud-init/gce-cloud-delete
+++ b/cloud-init/gce-cloud-delete
@@ -8,8 +8,10 @@
 #		K8S Cluster with bastion host						: bastion-host
 #		K8S Cluster, bastion-host, cloud-resourses			: all
 #		K8S Cluster, bastion-host, cloud-resources, bucket	: all-with-bucket
+#	$4 => delete cascading resources in case of errors
+#		delete parent even if error while deleting chield resource	: forced
 
-if [[ ${#} -lt 3 ]]; then
+if [[ ${#} -lt 4 ]]; then
 	echo "ERROR: Insufficient command parameters provided.  Exiting..."
 	exit 1
 fi
@@ -17,6 +19,7 @@ fi
 providedDigikubeCodeRawRepoUrl=${1}
 providedDigikubeConfigFileRef=${2}
 deleteChoice=${3}
+isForced=${4}
 
 DIGIKUBE_BASE_CONFIG="digikube-base-config.yaml"
 DELETE_CLUSTER_COMMAND="~/digikube/cluster/digiops cluster delete"
@@ -344,51 +347,82 @@ esac
 if [[ "${deleteCluster}" = "yes" ]]; then
 	
 	echo "INFO: Attempting to delete kubernetes cluster (${digikubeClusterFullName})"
+	canSshBastionHost="no"
 	bastionStatus=$(gcloud compute instances describe ${digikubeBastionHostName} --zone=${digikubeCloudProjectZone} | grep "status: RUNNING")
 	__returnCode=$?
 	if [[ ${__returnCode} -gt 0 ]]; then
-		echo "ERROR: Error while checking the bastion host status.  Exiting..."
-		exit ${__returnCode}
-	fi
-	if [[ "${bastionStatus}" == "status: RUNNING" ]]; then
-		echo "INFO: Tryining to delete cluster through bastion host (${digikubeBastionHostName})"
+		echo "ERROR: Error while checking the bastion host status.  Error code: ${__returnCode}"
+		if [[ "${isForced}" != "yes" ]]; then
+			echo "Exiting Digikube deletion..."
+			exit ${__returnCode}
+		fi
 	else
-		#TO DO: Need to check for shutdown status.... currently assuming it is in shutdown status.
-		echo "INFO: The current status of bastion host is ${bastionStatus}.  Attempting to start bastion host."
-		gcloud compute instances start ${bastionHostName} --zone=${digikubeCloudProjectZone}
-		__returnCode=$?
-		if [[ ${__returnCode} -gt 0 ]]; then
-			echo "ERROR: Error while starting bastion host.  Exiting..."
-			exit ${__returnCode}
-		fi
-		bastionStatus=$(gcloud compute instances describe ${bastionHostName} --zone=${digikubeCloudProjectZone} | grep "status: RUNNING")
-		__returnCode=$?
-		if [[ ${__returnCode} -gt 0 ]]; then
-			echo "ERROR: Error while checking the bastion host status.  Exiting..."
-			exit ${__returnCode}
-		fi
 		if [[ "${bastionStatus}" == "status: RUNNING" ]]; then
-			echo "INFO: Attempting to delete cluster through bastion host ${bastionHostName}"
+			echo "INFO: Tryining to delete cluster through bastion host (${digikubeBastionHostName})"
+			canSshBastionHost="yes"
 		else
-			echo "ERROR: Not able to access bastion host ${bastionHostName}.  The current status is ${bastionStatus}"
-			exit 1
+			#TO DO: Need to check for shutdown status.... currently assuming it is in shutdown status.
+			echo "INFO: The current status of bastion host is ${bastionStatus}.  Attempting to start bastion host."
+			gcloud compute instances start ${bastionHostName} --zone=${digikubeCloudProjectZone}
+			__returnCode=$?
+			if [[ ${__returnCode} -gt 0 ]]; then
+				echo "ERROR: Error while starting bastion host.   Error code: ${__returnCode}"
+				if [[ "${isForced}" != "yes" ]]; then
+					echo "Exiting Digikube deletion..."
+					exit ${__returnCode}
+				fi
+			else
+				bastionStatus=$(gcloud compute instances describe ${bastionHostName} --zone=${digikubeCloudProjectZone} | grep "status: RUNNING")
+				__returnCode=$?
+				if [[ ${__returnCode} -gt 0 ]]; then
+					echo "ERROR: Error while checking the bastion host status.  Error code: ${__returnCode}"
+					if [[ "${isForced}" != "yes" ]]; then
+						echo "Exiting Digikube deletion..."
+						exit ${__returnCode}
+					fi
+				else
+					if [[ "${bastionStatus}" == "status: RUNNING" ]]; then
+						echo "INFO: Attempting to delete cluster through bastion host ${bastionHostName}"
+						canSshBastionHost="yes"
+					else
+						echo "ERROR: Not able to access bastion host ${bastionHostName}.  The current status is ${bastionStatus}"
+						if [[ "${isForced}" != "yes" ]]; then
+							echo "Exiting Digikube deletion..."
+							exit ${__returnCode}
+						fi
+					fi
+				fi
+			fi
 		fi
 	fi
 	
-	echo "INFO: Attempting to delete Digikube K8S cluster."
-	echo "gcloud --quiet compute ssh ${bastionHostName} --zone=${digikubeCloudProjectZone} --command=${DELETE_CLUSTER_COMMAND}"
-	gcloud --quiet compute ssh ${bastionHostName} --zone=${digikubeCloudProjectZone} --command="${DELETE_CLUSTER_COMMAND}"
-	__returnCode=$?
-	if [[ ${__returnCode} -eq 0 ]]; then
-		echo "INFO: Deleted the Digikube cluster."
-	else
-		if [[ ${__returnCode} -eq 255 ]]; then
-			echo "ERROR: Error while performing ssh on bastion host."
-			exit 1
+	if [[ "${canSshBastionHost}" == "yes" ]]; then
+		echo "gcloud --quiet compute ssh ${bastionHostName} --zone=${digikubeCloudProjectZone} --command=${DELETE_CLUSTER_COMMAND}"
+		gcloud --quiet compute ssh ${bastionHostName} --zone=${digikubeCloudProjectZone} --command="${DELETE_CLUSTER_COMMAND}"
+		__returnCode=$?
+		if [[ ${__returnCode} -eq 0 ]]; then
+			echo "INFO: Deleted the Digikube cluster."
 		else
-			echo "ERROR: Error while deleting the Digikube cluster."
-			exit ${__returnCode}
+			if [[ ${__returnCode} -eq 255 ]]; then
+				echo "ERROR: Error while performing ssh on bastion host.  Error code: ${__returnCode}"
+				if [[ "${isForced}" != "yes" ]]; then
+					echo "Exiting Digikube deletion..."
+					exit ${__returnCode}
+				else
+					echo "WARN: Skipping cluster deletion due to error while using the bastion host.  Check and delete the cluster resources manually."
+				fi
+			else
+				echo "ERROR: Error while deleting the Digikube cluster.  Error code: ${__returnCode}"
+				if [[ "${isForced}" != "yes" ]]; then
+					echo "Exiting Digikube deletion..."
+					exit ${__returnCode}
+				else
+					echo "WARN: Skipping cluster deletion due to error while using the bastion host.  Check and delete the cluster resources manually."
+				fi
+			fi
 		fi
+	else
+		echo "WARN: Skipping cluster deletion due to error while using the bastion host.  Check and delete the cluster resources manually."
 	fi
 else
 	echo "INFO: Kubernetes cluster (${digikubeClusterFullName}) not to be deleted"
