Update helm-chart-om

diff --git a/cluster/sys-apps-om/helm-chart-om b/cluster/sys-apps-om/helm-chart-om
--- a/cluster/sys-apps-om/helm-chart-om
+++ b/cluster/sys-apps-om/helm-chart-om
@@ -25,11 +25,28 @@ function create {
 	chart_values_file=${digi_dir}config/sys-apps/${chart_values}
 	release_namespace=$(get-config-value "cluster.sysApps.${sys_app_name}.deploymentEngine.namespace")
 	
-	echo "helm install ${release_name} ${chart_name} --namespace ${release_namespace} -f ${chart_values_file}"
-	helm repo add stable ${chart_repo}
-	helm repo update
-	helm install ${release_name} ${chart_name} --namespace ${release_namespace} -f ${chart_values_file}
+	kubectl get namespace ${release_namespace}
+	if [[ ${?} -gt 0 ]]; then
+		echo "Namespace not available: ${release_namespace}.  Creating new"
+		kubectl create namespace ${release_namespace}
+		if [[ ${?} -gt 0 ]]; then
+			echo "Error while creating namespace: ${release_namespace}.  Aborting."
+			exit 1
+		else
+			echo "Created namespace: ${release_namespace}"
+		fi
+	fi
 	
+	kubectl get deployment ${release_name} --namespace ${release_namespace}
+	if [[ ${?} -gt 0 ]]; then
+		echo "helm install ${release_name} ${chart_name} --namespace ${release_namespace} -f ${chart_values_file}"
+		helm repo add stable ${chart_repo}
+		helm repo update
+		helm install ${release_name} ${chart_name} --namespace ${release_namespace} -f ${chart_values_file}
+	else
+		echo "Release already available with name: ${release_namespace}.  Please delete it or use update command."
+		exit 1
+	fi
 }
 
 function delete {
@@ -42,9 +59,20 @@ function delete {
 	release_name=$(get-config-value "cluster.sysApps.${sys_app_name}.deploymentEngine.releaseName")
 	release_namespace=$(get-config-value "cluster.sysApps.${sys_app_name}.deploymentEngine.namespace")
 	
-	echo "helm delete ${release_name} --namespace ${release_namespace}"
-	helm delete ${release_name} --namespace ${release_namespace}	
+	kubectl get namespace ${release_namespace}
+	if [[ ${?} -gt 0 ]]; then
+		echo "Namespace not available: ${release_namespace}.  Aborting"
+		exit 1
+	fi
 	
+	kubectl get deployment ${release_name} --namespace ${release_namespace}
+	if [[ ${?} -gt 0 ]]; then
+		echo "No release available with name: ${release_name}. Aborting."
+		exit 1
+	else
+		echo "helm delete ${release_name} --namespace ${release_namespace}"
+		helm delete ${release_name} --namespace ${release_namespace}
+	fi
 }
 
 shell_command_option=${2}
