Update digiops

diff --git a/cluster/digiops b/cluster/digiops
--- a/cluster/digiops
+++ b/cluster/digiops
@@ -51,23 +51,23 @@ function validate-cluster {
     #Function to validate the cluster.
     __function_name="cluster/digiops.validate-cluster"
     
-#    get-cluster-config
-#    if [[ $? -gt 0 ]]; then
-#        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
-#        exit 1
-#    fi
-#
-#    #First check if cluster available with the same name
-#    kops get cluster                     \
-#        --name=${kops_cluster_name}      \
-#        --state=${kops_state_store}
-#
-#    __kops_exit_status=$?
-#    if [[ ${__kops_exit_status} -gt 0 ]]; then
-#        log_it "${__function_name}" "installer" "ERR" "2110" "No cluster available for validation"
-#        exit 1
-#    fi
-#    
+    get-cluster-config
+    if [[ $? -gt 0 ]]; then
+        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
+        exit 1
+    fi
+
+    #First check if cluster available with the same name
+    kops get cluster                     \
+        --name=${kops_cluster_name}      \
+        --state=${kops_state_store}
+
+    __kops_exit_status=$?
+    if [[ ${__kops_exit_status} -gt 0 ]]; then
+        log_it "${__function_name}" "installer" "ERR" "2110" "No cluster available for validation"
+        exit 1
+    fi
+    
 #    __kops_exit_status=1
 #    __loop_count=0
 #    __max_loop_count=30
