Update digiops

diff --git a/cluster/digiops b/cluster/digiops
--- a/cluster/digiops
+++ b/cluster/digiops
@@ -49,46 +49,46 @@ function validate-cluster {
     #Function to validate the cluster.
     __function_name="cluster/digiops.validate-cluster"
     
-    get-cluster-config
-    if [[ $? -gt 0 ]]; then
-        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
-        exit 1
-    fi
-
-    #First check if cluster available with the same name
-    kops get cluster                     \
-        --name=${kops_cluster_name}      \
-        --state=${kops_state_store}
-
-    __kops_exit_status=$?
-    if [[ ${__kops_exit_status} -gt 0 ]]; then
-        log_it "${__function_name}" "installer" "ERR" "2110" "No cluster available for validation"
-        exit 1
-    fi
-    
-    __kops_exit_status=1
-    __loop_count=0
-    __max_loop_count=30
-    __loop_sleep_duration=10 
-    
-    while [ ${__kops_exit_status} -gt 0 ]
-    do
-        kops validate cluster --state=${kops_state_store}
-        __kops_exit_status=$?
-        __loop_count=${__loop_count}+1
-        if [[ ${__loop_count} -gt ${__max_loop_count} ]]; then
-            break
-        fi
-        sleep ${__loop_sleep_duration}
-    done
-    
-    if [[ ${__loop_count} -gt ${__max_loop_count} ]]; then
-        #This is timeout condition
-        log_it "${__function_name}" "installer" "ERR" "2110" "Timeout while validating cluster"
-        exit 1
-    else
-        log_it "${__function_name}" "installer" "DEBUG" "2110" "Cluster validated"
-    fi
+#    get-cluster-config
+#    if [[ $? -gt 0 ]]; then
+#        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
+#        exit 1
+#    fi
+#
+#    #First check if cluster available with the same name
+#    kops get cluster                     \
+#        --name=${kops_cluster_name}      \
+#        --state=${kops_state_store}
+#
+#    __kops_exit_status=$?
+#    if [[ ${__kops_exit_status} -gt 0 ]]; then
+#        log_it "${__function_name}" "installer" "ERR" "2110" "No cluster available for validation"
+#        exit 1
+#    fi
+#    
+#    __kops_exit_status=1
+#    __loop_count=0
+#    __max_loop_count=30
+#    __loop_sleep_duration=10 
+#    
+#    while [ ${__kops_exit_status} -gt 0 ]
+#    do
+#        kops validate cluster --state=${kops_state_store}
+#        __kops_exit_status=$?
+#        __loop_count=${__loop_count}+1
+#        if [[ ${__loop_count} -gt ${__max_loop_count} ]]; then
+#            break
+#        fi
+#        sleep ${__loop_sleep_duration}
+#    done
+#    
+#    if [[ ${__loop_count} -gt ${__max_loop_count} ]]; then
+#        #This is timeout condition
+#        log_it "${__function_name}" "installer" "ERR" "2110" "Timeout while validating cluster"
+#        exit 1
+#    else
+#        log_it "${__function_name}" "installer" "DEBUG" "2110" "Cluster validated"
+#    fi
 
 }
 
