Update digiops

diff --git a/cluster/digiops b/cluster/digiops
--- a/cluster/digiops
+++ b/cluster/digiops
@@ -210,25 +210,25 @@ function delete-cluster {
     #Function to create cluster.
     __function_name="cluster/digiops.delete-cluster"
 
-#    log_it "${__function_name}" "installer" "INFO" "2110" "Started the cluster deletion process"
-#
-#    get-cluster-config
-#    if [[ $? -gt 0 ]]; then
-#        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
-#        exit 1
-#    fi
-#
-#    #First check if cluster available with the same name
-#    kops get cluster                     \
-#        --name=${kops_cluster_name}      \
-#        --state=${kops_state_store}
-#
-#    __kops_exit_status=$?
-#    if [[ ${__kops_exit_status} -gt 0 ]]; then
-#        log_it "${__function_name}" "installer" "ERR" "2110" "No cluster available for deletion"
-#        exit 1
-#    fi
-#    
+    log_it "${__function_name}" "installer" "INFO" "2110" "Started the cluster deletion process"
+
+    get-cluster-config
+    if [[ $? -gt 0 ]]; then
+        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
+        exit 1
+    fi
+
+    #First check if cluster available with the same name
+    kops get cluster                     \
+        --name=${kops_cluster_name}      \
+        --state=${kops_state_store}
+
+    __kops_exit_status=$?
+    if [[ ${__kops_exit_status} -gt 0 ]]; then
+        log_it "${__function_name}" "installer" "ERR" "2110" "No cluster available for deletion"
+        exit 1
+    fi
+    
 #    kops delete cluster                 \
 #        --name=${kops_cluster_name}     \
 #        --state=${kops_state_store}     \
@@ -324,3 +324,15 @@ function start-cluster {
 #    update-cluster
     
 }
+
+if [[ $# -gt 0 ]]; then
+    
+    action_option=${1}
+    case ${action_option} in 
+		"delete-cluster")
+                            delete-cluster
+                            ;;
+        *)
+    esac
+
+fi
