Update digiops

diff --git a/cluster/digiops b/cluster/digiops
--- a/cluster/digiops
+++ b/cluster/digiops
@@ -348,34 +348,54 @@ function start-cluster {
 
     #Function to create cluster.
     __function_name="cluster/digiops.start-cluster"
-#
-#    log_it "${__function_name}" "installer" "INFO" "2110" "Started the cluster start process"#
-#
-#    get-cluster-config
-#    if [[ $? -gt 0 ]]; then
-#        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
-#        exit 1
-#    fi
-#
-#    #First check if cluster available with the same name
-#    kops get cluster                     \
-#        --name=${kops_cluster_name}      \
-#        --state=${kops_state_store}
-#
-#    __kops_exit_status=$?
-#    if [[ ${__kops_exit_status} -gt 0 ]]; then
-#        log_it "${__function_name}" "installer" "ERR" "2110" "No cluster available for start"
-#        exit 1
-#    fi
-#    
-#    ig_base_master_config="${digi_dir}config/ig-base-master-config-template.yaml"
-#    ig_base_node_config="${digi_dir}config/ig-base-node-config-template.yaml"
-#    
-#    kops replace -f="${ig_base_master_config}" --state=${kops_state_store}
-#    kops replace -f="${ig_base_node_config}" --state=${kops_state_store}
-#
-#    update-cluster
+
+    log_it "${__function_name}" "installer" "INFO" "2110" "Started the cluster start process"#
+
+    get-cluster-config
+    if [[ $? -gt 0 ]]; then
+        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
+        exit 1
+    fi
+
+    #First check if cluster available with the same name
+    kops get cluster                     \
+        --name=${kops_cluster_name}      \
+        --state=${kops_state_store}
+
+    __kops_exit_status=$?
+    if [[ ${__kops_exit_status} -gt 0 ]]; then
+        log_it "${__function_name}" "installer" "ERR" "2110" "No cluster available for start"
+        exit 1
+    fi
     
+    ig_master_config="${digi_dir}config/templates/ig-master-config-template.yaml"
+    ig_node_config="${digi_dir}config/templates/ig-node-config-template.yaml"
+    
+    #Need to export env var due to envsubst
+    export kops_cluster_name=${kops_cluster_name}
+    export kops_associate_public_ip=${kops_associate_public_ip}
+    export kops_region=${kops_region}
+    
+    export kops_master_image=${kops_master_image}
+    export kops_master_size=${kops_master_size}
+    export kops_master_count_max=${kops_master_count_max}
+    export kops_master_count_min=${kops_master_count_min}
+    export kops_master_zones=${kops_master_zones}
+    export kops_master_volume_size=${kops_master_volume_size}
+    export kops_master_zones=${kops_master_zones}
+    
+    export kops_node_image=${kops_node_image}
+    export kops_node_size=${kops_node_size}
+    export kops_node_count_max=${kops_node_count_max}
+    export kops_node_count_min=${kops_node_count_min}
+    export kops_node_volume_size=${kops_node_volume_size}
+    export kops_worker_zones=${kops_worker_zones}
+    
+    cat ${ig_zero_master_config} | envsubst | kops replace -f - --state=${kops_state_store}
+    cat ${ig_zero_node_config} | envsubst | kops replace -f - --state=${kops_state_store}
+
+    update-cluster
+ 
 }
 
 if [[ $# -gt 0 ]]; then
