Update digiops

diff --git a/cluster/digiops b/cluster/digiops
--- a/cluster/digiops
+++ b/cluster/digiops
@@ -144,11 +144,11 @@ function create-cluster {
     log_it "${__function_name}" "installer" "INFO" "2110" "Started the cluster installation process"
 
     get-cluster-config
-#    if [[ $? -gt 0 ]]; then
-#        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
-#        exit 1
-#    fi
-#
+    if [[ $? -gt 0 ]]; then
+        log_it "${__function_name}" "installer" "ERR" "2110" "Error while getting cluster configuration details"
+        exit 1
+    fi
+
 #    #First check if cluster available with the same name
 #    kops get cluster                     \
 #        --name=${kops_cluster_name}      \
