Update krew-installer

diff --git a/installer/krew-installer b/installer/krew-installer
--- a/installer/krew-installer
+++ b/installer/krew-installer
@@ -18,24 +18,33 @@ log_it "${__function_name}" "installer" "DEBUG" "1115" "Target version of krew t
 krew_download_url=$(get-config-value "component.krew.url")
 log_it "${__function_name}" "installer" "DEBUG" "1120" "Krew download site is: ${krew_download_url}"
 
+krew_existing_version=$(kubectl krew version | grep GitTag | cut -d "v" -f 2)
+__return_code=$?
+if [[ __return_code -gt 0 ]]; then
+	echo "Error while checking krew version.  Ignorring."
+fi
 
-#TO DO: Externalize the following code to get values from config
+if [[ -z ${krew_existing_version} ]]; then
+	#set -x
+	cd "$(mktemp -d)"
+	curl -fsSLO "${krew_download_url}.{tar.gz,yaml}"
+	tar zxvf krew.tar.gz
+	KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64"
+	"$KREW" install --manifest=krew.yaml --archive=krew.tar.gz
+	"$KREW" update
+	export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
+else
+	if [[ "$krew_existing_version" = "$krew_download_version" ]]; then
+		log_it "${__function_name}" "installer" "INFO" "1235" "Pre-existing krew version is same as expected target version: ${krew_download_version}. Using the pre-existing kops binary."
+	else
+		log_it "${__function_name}" "installer" "ERR" "1240" "Pre-existing krew version is: ${krew_existing_version}.  Target version of krew is: ${krew_download_version}. Aborting krew installation.  Remove existing krew binary and rerun the installation."
+		exit 1
+	fi 
+fi
 
-set -x
-cd "$(mktemp -d)"
-curl -fsSLO "${krew_download_url}.{tar.gz,yaml}"
-tar zxvf krew.tar.gz
-KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64"
-"$KREW" install --manifest=krew.yaml --archive=krew.tar.gz
-"$KREW" update
-
-export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
-
-isExported=$(cat ~/.bashrc | grep 'export PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH')
-echo "${isExported}"
-if [[ -z ${isExported} ]]; then
+isPATHUpdate=$(cat ~/.bashrc | grep 'export PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH')
+if [[ -z ${isPATHUpdated} ]]; then
   echo 'export PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH' >> ~/.bashrc 
 fi
-#source ~/.bashrc
 
 log_it "${__function_name}" "installer" "DEBUG" "1120" "Krew installed"
