Update main-installer

diff --git a/installer/main-installer b/installer/main-installer
--- a/installer/main-installer
+++ b/installer/main-installer
@@ -5,19 +5,76 @@ base_dir=~/
 digi_dir=${base_dir}digikube/
 digi_ops_executer=${digi_dir}cluster/digiops
 
-kubectl_installer=${digi_dir}installer/kubectl-installer.sh
+#Install kubectl
+kubectl_installer=${digi_dir}installer/kubectl-installer
 ${kubectl_installer}
 if [[ $? -gt 0 ]]; then
     exit 1
 fi
 
-kops_installer=${digi_dir}installer/kops-installer.sh
+#Install kops
+kops_installer=${digi_dir}installer/kops-installer
 ${kops_installer}
 if [[ $? -gt 0 ]]; then
     exit 1
 fi
 
+#Install helm
+helm_installer=${digi_dir}installer/helm-installer
+${kops_installer}
+if [[ $? -gt 0 ]]; then
+    exit 1
+fi
+
+#Install cluster
 ${digi_ops_executer} cluster create
 if [[ $? -gt 0 ]]; then
     exit 1
 fi
+
+#Install sys-apps
+#ingress-controller
+${digi_ops_executer} sys-apps ingress-controller create
+if [[ $? -gt 0 ]]; then
+    echo "Some error"
+fi
+
+#kubernetes-dashboard
+${digi_ops_executer} sys-apps kubernetes-dashboard create
+if [[ $? -gt 0 ]]; then
+    echo "Some error"
+fi
+
+#GAP
+${digi_ops_executer} sys-apps gap create
+if [[ $? -gt 0 ]]; then
+    echo "Some error"
+fi
+
+#ELK
+${digi_ops_executer} sys-apps elk create
+if [[ $? -gt 0 ]]; then
+    echo "Some error"
+fi
+
+#Install platform-apps
+#MongoDB Operator
+
+#Kubeflow
+
+#Kafka Operator
+
+#NodeJS app operator
+
+#LAMP stack operator
+
+#Polyaxon
+
+#...
+
+#Install client tools
+#???
+
+
+#Install predefined user-apps
+#
